apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-ingress.yaml

namespace: store

patches:
  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: azure-kvname-user-msi
        namespace: store
      spec:
        parameters:
          userAssignedIdentityID: <client-id>
          keyvaultName: <key-vault-name>
          tenantId: <tenat-id>
    target: 
      kind: SecretProviderClass
      name: azure-kvname-user-msi
  